apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp
spec:
  myASN: 4200000000
  peerASN: 4200000000
  peerAddress: 10.7.0.3
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp 
