apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data
  namespace: grocy
spec:
  storageClassName: ceph-filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
