apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry

spec:
  interval: 1h
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: registry
      interval: 1h

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - registry.chaosdorf.space
      paths:
      - /
      tls:
      - secretName: ingress-tls
        hosts:
        - registry.chaosdorf.space

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

    persistence:
      enabled: true
      size: 20Gi
      storageClass: 'ceph-block'

    metrics:
      enabled: true
      port: 5001

    garbageCollect:
      enabled: true
      deleteUntagged: true
      schedule: "0 1 * * *"
