apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8up

spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      sourceRef:
        kind: HelmRepository
        name: k8up
      interval: 1h

  values: {}
