---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prittstift
  name: fonts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
