apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freepbx-metrics
resources:
- helm-release.yaml
- helm-repository.yaml
- namespace.yaml
configMapGenerator:
- name: dashboard-freepbx
  files:
  - dashboard-freepbx.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
