apiVersion: v1
kind: Service
metadata:
  name: samba-adapter
  namespace: samba-adapter
  annotations:
    external-dns.alpha.kubernetes.io/hostname: smb.fileserver.chaosdorf.space.
spec:
  type: LoadBalancer
  selector:
    app: samba-adapter
  ports:
  - name: smb
    protocol: TCP
    port: 445
    targetPort: smb
