apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-replicas
spec:
  background: true
  rules:
  - name: set-replicas
    match:
      any:
      - resources:
          kinds:
          - Deployment
    exclude:
      any:
      - resources:
          namespaces:
          - rook-cluster
          - rook-ceph
    mutate:
      patchStrategicMerge:
        spec:
          replicas: 3

